### ISSUE TITLE
Forthcoming additions

### ISSUE THREAD

**Issue by jacobzipper** [shreyascasturi/emacs_config#1]
Thank you sir please fix

**Comment by shreyascasturi** [comment]
Forthcoming additions to emacs_config:

Olivetti mode integration, for simple writing.

AUCTeX integration as well (requires texlive and TeX associated packages)

EIN - an environment to edit/use Jupyter/IPython notebooks. This hasn't been working, but I believe that by carefully uninstalling and reinstalling the specific python packages and understanding how Jupyter works, we can get this set up quickly.

BONUS:

Magit, so that Git works splendidly.

If there are further questions on the file, or perhaps one wants to learn more about how to use GNU Emacs, please refer to this manual: https://www.gnu.org/software/emacs/manual/html_node/emacs/index.html



*Please support free software*
